project:
  type: website

website:
  title: "jedi-read-s26"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: organizers.qmd
        text: Organizers
      - href: https://causeweb.org/jedi/
        text: JEDI-CAUSE

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



