project:
  type: website

website:
  title: "JEDI-CAUSE reading group"
  favicon: img/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: organizers.qmd
        text: Organizers
      - text: <a href = "https://causeweb.org/jedi/" target = "_blnak">JEDI-CAUSE</a>
        href: "#" 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



